### ISSUE TITLE
p8b pinetime-mcuboot-app-dfu-1.9.0.zip gatt error 133 in recovery

### ISSUE THREAD

**Issue by LoriLori** [StarGate01/p8b-infinitime#1]
Can't connect via nrf connect (two different phones) or linux getting gatt error 133 or 
[CHG] Device XX:XX:XX:XX:XX:XX Connected: yes
Failed to connect: org.bluez.Error.Failed
I think LFRC doesn't get calibrated properly.

**Comment by StarGate01** [comment]
Are you able to connect to the watch and list its services using NRF Connect, or does the connection end immediately?

**Comment by LoriLori** [comment]
No connection using using NRF Connect. Connection attempt takes 14s and ends with 133, turned off/on phone and blue tooth. 
Opened watches so I can investigate.

**Comment by StarGate01** [comment]
Okay, thanks for the test. The LF clock calibration should work, but there might be an issue with the binaries on GitHub. I'll recompile from the new branch (a lot of refactoring is currently taking place in order to upstream P8 support into the official InfiNitime source code, see https://github.com/InfiniTimeOrg/InfiniTime/pulls?q=is%3Apr+author%3AStarGate01 ).

**Comment by ildar** [comment]
I've seen a similar problem with P8b FW on my P8(a) watch that HAS LF.
@LoriLori you should use P8a FW if it works. Bootloader features should
save you in case of the non-working FW.

**Comment by StarGate01** [comment]
Please note that on LF crystal builds, the recovery uses the LF crystal as well. In theory, the LFRC builds should run on devices which have a crystal just as well, but I have seen the contention issues @ildar is describing.

I will be updating the device names to MOY-*, to hopefully reduce confusion on what firmware to use.

**Comment by LoriLori** [comment]
Sorry, I can't test. Opening a watch I caused damage.
