### ISSUE TITLE
Help with P8-b MOY-GAM5-2.3.0 Variant

### ISSUE THREAD

**Issue by playlogo** [StarGate01/p8b-infinitime#10]
Hey,
I recently picked up a P8-b with 'MOY-GAM5-2.3.0' firmware and want to flash Infinitime onto it. 
Have you encountered this model before, and can you recommend a specific build ? If not, could I try builds for different hardware versions without risking bricking the watch and having to open it ?
Thanks for your help and this awesome port!

**Comment by StarGate01** [comment]
Hey, unfortunately I did not encounter that watch before. Which charging method does it use? A magnetic bay or a clip?

In order to not brick Bluetooth, pick a build with LF clock = RC  (see https://github.com/StarGate01/p8b-infinitime/blob/master/HardwareVariants.md), as we cant be sure if the watch contains a proper XTAL.

Let me know what you find out, then I'll add your model to the list.

**Comment by playlogo** [comment]
Sorry for the later response, but it seems like this P8 variant is not using the nrf52 but something else instead (I think gr5515, but I could be wrong).
Comparing it with a nrf52 P8, its default firmware also seems way more responsive, and it is using a small magnetic charging clip.
